### ISSUE TITLE
What are the nginx configurations for SSE

### ISSUE THREAD

**Issue by titoc** [ralscha/sse-eventbus#18]
This is more of a question than an issue. What should be the nginx conf required for a url path for SSE.
For example:  /events url path in nginx should be configured with which options.
Thanks !

**Comment by ralscha** [comment]
I use this configuration in my application

```
  location / {
    proxy_pass http://127.0.0.1:8081;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_buffering off;
    proxy_read_timeout 410s;
  }
```

The important settings are `proxy_buffering` and `proxy_read_timeout`
