### ISSUE TITLE
Spring bug causes controller to re-dispatch connections

### ISSUE THREAD

**Issue by smithtonson** [ralscha/sse-eventbus#2]
There's a race-condition in Spring prior to V4.3.13 that causes methods that return an SseEmitter to re-dispatch after the client disconnects. Upgrading the project to use Spring 4.3.13 should fix this provided that emitter.completeWithError() *is not* called.

I.e. in SseEventBus.java, lines 294 & 299 should be noop and commented out. (Since the emitter is already completed)

see [SPR-16058](https://jira.spring.io/browse/SPR-16058) and [this comment](https://jira.spring.io/browse/SPR-16058?focusedCommentId=155331&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-155331)

**Comment by ralscha** [comment]
Line 294 is a workaround that I needed for Microsoft Edge. 
This simply closes the event source connection after each message.
