### ISSUE TITLE
Support for Unicast over SSE

### ISSUE THREAD

**Issue by Zaky7** [ralscha/sse-eventbus#20]
hi, want to use unicast. 
How can I use this library for unicasting?. We can create a new method for publishing to a single client.

**Comment by ralscha** [comment]
Hi

What you need to do is in the register method store the id somewhere. 

```java
 @GetMapping("/register/{id}")
  public SseEmitter register(@PathVariable("id") String id) {
     // id is the client id. store it somewhere
  }
```

Then in the publishing code you specify the client which should receive the event

```java
		SseEvent.builder()
		    .event("msg").data("payload")
		    .addClientIds("client1")  // or multiple client .addClientIds("client1", "client2", "client3")
		    .build();
```

**Comment by Zaky7** [comment]
thanks I will give it a try

**Comment by Zaky7** [comment]
it works thanks @ralscha
