### ISSUE TITLE
Whether to support deployment on multiple servers or microservices in spring cloud

### ISSUE THREAD

**Issue by wideweide** [ralscha/sse-eventbus#21]
n order to improve concurrency, sometimes you need to deploy a plurality of spring cloud microservices, but SseEmitter is created in the microservices example of a static variable, sse-event can be deployed in multiple microservices node for use? How to navigate to a specific instance then to send message?

**Comment by wideweide** [comment]
thanks for reply, pub/sub is a useful solution.
Do you test the SseEmitter's Concurrency? 
It seems  https://www.nginx.com/resources/wiki/modules/push_stream support sse/event source,more simple,more concurrency..

**Comment by ralscha** [comment]
There is a [test with multiple subscribers](https://github.com/ralscha/sse-eventbus/blob/master/src/test/java/ch/rasc/sse/eventbus/IntegrationTest.java).

The nginx module looks interesting. 

For a new project I would check out Centrifugal. 
https://centrifugal.dev/

**Comment by wideweide** [comment]
> There is a [test with multiple subscribers](https://github.com/ralscha/sse-eventbus/blob/master/src/test/java/ch/rasc/sse/eventbus/IntegrationTest.java).
> 
> The nginx module looks interesting.
> 
> For a new project I would check out Centrifugal. https://centrifugal.dev/

thanks for suggest
It seems SseEmitter is not a good choice, and found another choise nchan : kind of like centifugal
* nchan vs nginx-push-stream-module: https://github.com/slact/nchan/issues/116

How to choose is a problem now...
