### ISSUE TITLE
Distributed SseEventBus

### ISSUE THREAD

**Issue by HJK181** [ralscha/sse-eventbus#23]
We successfully use your library in our project, with only one drawback: The service handling the SSE-Connections can't be scaled as the client registration(s) live in memory inside `SseEventBus#clients` map.

Therefore how would you solve the distribution problem? From what I see so far, I came up with the following:
1. Use some Pub/Sub framework in between and let every running instance of the service subscribe to a topic where it receives events with the client ID matching the registered clients in the event bus. Those events are then forwarded to the `EventBus#handleEvent` method if the client ID is registered on the particular service.
2. Extend the `SseEventBusConfigurer` in the library in order to also pass a custom clients Map. I think all other data structures inside `SseEventBus` can already be provided with different distributed data structures, e.g. Redis/Hazelcast implementation of distributed queues, `SubscriptionRegistry`...

Do you have any other suggestions? 

Thank you for the great work.

**Comment by ralscha** [comment]
That sounds good. If you can provide a pull request I will merge it and release a new version.
Unfortunately I currently don't have time to do the refactor.

I personaly don't use the library anymore.  
I switched my project to [Centrifugo](https://centrifugal.dev/). 
Highly recommend it, works amazing for realtime updates.

**Comment by HJK181** [comment]
Thanks for the quick response and the new release. Could you please also publish the artifact to maven central? https://mvnrepository.com/artifact/ch.rasc/sse-eventbus

Then, the issue can be closed :)

**Comment by ralscha** [comment]
It's released. Version 2.0.1

**Comment by HJK181** [comment]
Still can't find it with the above link.

**Comment by ralscha** [comment]
https://central.sonatype.com/artifact/ch.rasc/sse-eventbus/2.0.1
