### ISSUE TITLE
missing ImmutableSseEvent class

### ISSUE THREAD

**Issue by americanstone** [ralscha/sse-eventbus#5]
SseEvent and IntegrationTest are missing ImmutableSseEvent, so the project is not able to compile

**Comment by ralscha** [comment]
ImmutableSseEvent is generated by the [Immutables](https://immutables.github.io/) library.
You find the class in the directory `target\generated-sources\annotations\ch\rasc\sse\eventbus` after a compile
```
   ./mvn compile
```

**Comment by americanstone** [comment]
ok, thanks.
